name: "2600 metros más cerca de las estrellas."

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Generic LuCI-APP
    runs-on: ubuntu-latest
    env:
      sdk_name: "openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64"
      project_name: "luci-app-pm"

    steps:
      - name: Checkout Code
        uses: actions/checkout@main

      - name: Install Build Dependencies
        uses: mokanove/mokanove/actions/luci-env@main

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: ${{ env.sdk_name }}

      - name: Clone Source Code
        uses: mokanove/mokanove/actions/clone@main
        with:
          sdk_name: ${{ env.sdk_name }}
          project_name: ${{ env.project_name }}

      - name: Get Version
        id: get_version
        run: |
          cd ${{ env.sdk_name }}/package/${{ env.project_name }}
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build!
        uses: mokanove/mokanove/actions/build@main
        with:
          sdk_name: ${{ env.sdk_name }}
          project_name: ${{ env.project_name }}

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: ${{ env.sdk_name }}/bin/packages/**/*.apk
          make_latest: true
          body: |
            # 📝 Release Notes
            - Upgrade SDK version to SNAPSHOT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
