name: "2600 metros más cerca de las estrellas."

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      project_name: "luci-app-pm"
      sdk_name: "openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64"

    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: ${{ env.project_name }}

      - name: Get Version
        id: get_version
        run: |
          cd ${{ env.project_name }}
          VERSION=$(grep -E "^PKG_VERSION[[:space:]]*:=" Makefile | sed -E 's/.*:=[[:space:]]*//' | tr -d '[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: ${{ env.sdk_name }}

      - name: Build!
        shell: bash
        run: |
          mv ${{ env.project_name }} ${{ env.sdk_name }}/package/
          cd ${{ env.sdk_name }}
          make package/${{ env.project_name }}/compile V=s -j$(nproc)

      - name: Release
        uses: softprops/action-gh-release@master
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: ${{ env.sdk_name }}/bin/packages/**/*.apk
          make_latest: true
          body: |
            # 📝 Release Notes
            - Some action change
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
